name: oidc-claims

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  print-claims:
    runs-on: ubuntu-latest
    steps:
      - name: Request OIDC token and print claims
        uses: google-github-actions/auth@v3
