name: workflow_call

on:
  workflow_call:
    inputs:
      in:
        type: string
    secrets:
      SECRET_IN:
      
permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: |
          echo "secrets inherit: ${{ secrets.FLAG }}"
          echo "secrets input: ${{ secrets.SECRET_IN }}"
      - run: |
          echo "env: ${{ env.FLAG }}"
      - run: |
          echo "inputs: ${{ inputs.in }}"
