name: workflow_call

on:
  workflow_call:
    inputs:
      in:
        type: string
    secrets:
      FLAG:
      
permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: echo "${{ secrets.FLAG }}"
      - run: echo "${{ env.FLAG }}"
      - run: echo "${{ inputs.in }}"
